version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-web-container
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      PORT: 3000
      JWT_SECRET: your_jwt_secret
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - init
    command: npm run dev

  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - init

volumes:
  postgres-data:

networks:
  init:
    driver: bridge
